web/router.ex
defmodule SimpleAuth.Router do
  use SimpleAuth.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :with_session do
  plug Guardian.Plug.VerifySession
  plug Guardian.Plug.LoadResource
  plug SimpleAuth.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # ...
  # ...
  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated,
         handler: SimpleAuth.GuardianErrorHandler
  end

  pipeline :admin_required do
    plug SimpleAuth.CheckAdmin
  end

# guest zone
  scope "/", SimpleAuth do
  pipe_through [:browser, :with_session]
  get "/", PageController, :index
  resources "/sessions", SessionController, only: [:new, :create,
                                                   :delete]
  resources "/users", UserController, only: [:new, :create]
  resources "/orders", OrderController
  resources "/orderdetails", DetailController

  get "/*path", PageController, :index

  get "/users*path", PageController, :index

end


# Other scopes may use custom stacks.
  # scope "/api", SimpleAuth do
  #   pipe_through :api
  # end
end

web/models/detail.ex
defmodule SimpleAuth.Detail do
use SimpleAuth.Web, :model
@alphabet Enum.concat([?0..?9, ?A..?Z, ?a..?z])

  schema "orders" do
    field :patient_name, :string
    field :patient_address, :string, default: ""
    field :patient_contact, :integer
    field :patient_email, :string
    field :pickup_date, :date
    field :patient_state, :string, default: ""
    field :patient_city, :string
    field :patient_zipcode, :integer
    field :pickup_time, :time
    field :order_number, :string
    field :courier_id, :integer
    field :order_status, :integer, default: 1
    field :user_id, :integer

     # has_many  :users, SimpleAuth.User
      # belongs_to :users, SimpleAuth.User

  end

  def changeset(struct,params \\ %{}) do
    struct
    |> cast(params, [
        :patient_name,
        :patient_address,
        :patient_contact,
        :patient_email,
        :pickup_date,
        :patient_state,
        :patient_city,
        :patient_zipcode,
        :pickup_time,
        :courier_id,
        :order_status,
        :order_number])
    |> validate_required(:patient_name)
    |> generate_random_number
  end

  def generate_random_number(struct) do
      order_number = get_field(struct, :order_number)
      alphabet = randstring(8);
      alphabet = "SD-#{alphabet}."
      put_change(struct, :order_number, alphabet)
  end

  def randstring(count) do
    # Technically not needed, but just to illustrate we're
    # relying on the PRNG for this in random/1
    :rand.seed(:exsplus, :os.timestamp())
    Stream.repeatedly(&random_char_from_alphabet/0)
    |> Enum.take(count)
    |> List.to_string()
  end

  defp random_char_from_alphabet() do
    Enum.random(@alphabet)
  end

end

web/controllers/detail_controller.ex
defmodule SimpleAuth.DetailController do
  use SimpleAuth.Web, :controller
  alias SimpleAuth.Order
  alias SimpleAuth.User
  alias SimpleAuth.UserRole

  plug :scrub_params, "detail" when action in [:create, :update]

   def action(conn, _) do
      apply(__MODULE__, action_name(conn),
            [conn, conn.params, conn.assigns.current_user])
    end

   def index(conn, _params, current_user) do
     orders =  Repo.all(Order)
     courier  =  Repo.all(User)
     render conn, "index.html", orders: orders , courier: courier
   end

   def show(conn, %{"id" => order_id}, current_user) do
     order =  Repo.get(Order, order_id)
     IO.inspect(order)
     changeset  =  Order.changeset(order)
     courier  =  Repo.all(User)
     render conn, "index.html", changeset: changeset ,  order: order , courier: courier
   end

   def edit(conn, %{"id" => order_id}, current_user) do
     order =  Repo.get(Order, order_id)
     IO.inspect(order)
     changeset  =  Order.changeset(order)
     courier  =  Repo.all(User)
     render conn, "edit.html", changeset: changeset ,  order: order , courier: courier
   end

   def update(conn, %{"id"=>order_id, "order"=>order},current_user) do
     old_order = Repo.get(Order, order_id)
     changeset = Order.changeset(old_order,order)
     courier  =  Repo.all(User)
     IO.inspect(order)
     case Repo.update(changeset) do
       {:ok,_order}->
       conn
       |> put_flash(:info, "Order Updated")
       |> redirect(to: order_path(conn, :index))
       {:error, changeset}->
         render conn, "edit.html", changeset: changeset , order:  old_order , courier: courier
     end
   end

end

web/views/detail_view.ex
defmodule SimpleAuth.DetailView do
  use SimpleAuth.Web, :view
end

web/templates/detail/edit.html.eex
<%= form_for @changeset, order_path(@conn, :update, @order), fn f -> %>
<%= hidden_input f, :order_status, value: "2" , class: "form-control" %>
<div class="patient_form">
  <h5> <strong>Cancel Order </strong> <%= @order.order_number %></h5> &nbsp
  <div class="form-row ">
    <div class="form-group col-md-12">
      <label for="inputEmail4">Comment</label>
      <%= textarea f, :order_cancel_description , required: 'required' ,  class: "form-control" , rows: "4" , cols: "50" %>
      <%= error_tag f, :order_cancel_description %>
    </div>
  </div>
</div>
<div class="Cancel-button">
  <a href="/orders" class="btn btn-primary btn-back cancel-btn">Cancel</a>
</div>

<%= submit "Submit", class: "btn btn-primary pull-right create-btn" %>
<% end %>

web/templates/detail/index.html.eex
<div id="page-wrapper">
  <details open>
    <summary>Action</summary>
    <ul class="summary-nav" style="display: flex;">
      <!-- # Fetching all the order_role from order status table
    </br>
      # 1 : New
      # 2 : Canceled
      # 3: Delivered
      # 4: Undelivered
      </br> -->
      <%= if @order.order_status ==2 do %>
      <span class= "cancel-description"> <span style="font-weight: bold;"> Cancellation Comment: </span> <%= @order.order_cancel_description %></span>
      <% end %>
      <%= if @current_user.user_role_id !=3 && @order.order_status !=2 && @order.order_status !=3 do %>
      <div class="pharma-info-view">
        <li> <a class= "btn-sm btn-primary " href=<%= detail_path(@conn, :edit, @order) %> >Cancel</a></li>
        <li><a class= "btn-sm btn-primary " href=<%= order_path(@conn, :edit, @order) %> >Edit</a></li>
      </div>
      <% else %>

        <%= if @order.order_status ==3 do %>
          <span class= "done">  Order is Delivered </span>
            <% else %>
            <%= if @order.order_status ==2 do %>
              <span class= "Undelivered">  Order is Canceled </span>
                <% else %>
              <%= if @order.order_status !=3 do %>
                      <%= form_for @changeset,  order_path(@conn, :update, @order), [id: "form-undeliver"], fn f -> %>
                        <%= hidden_input f, :order_status, value: "3" , class: "form-control" %>
                        <%= submit "Delivered", class: "btn-sm btn-primary pull-right detail-deliver" %>
                      <% end %>

                    <%= form_for @changeset,  order_path(@conn, :update, @order), [id: "some-id"], fn f -> %>
                      <%= hidden_input f, :order_status, value: "4" , class: "form-control" %>
                      <%= submit "UnDelivered", class: "btn-sm btn-primary pull-right detail-deliver" %>
                  <% end %>
                <% end %>
            <% end %>
        <% end %>
      <% end %>
    </ul>
  </details>
  <!-- Specifying an 'open' attribute will make all the content visible when the page loads -->
  <details open>
    <summary>Order #<%= @order.order_number %></summary>
    <table>
      <tr>
        <th scope="row">Pickup Date & Time</th>
        <td><%= @order.pickup_date %>-<%= @order.pickup_time %> </td>
      </tr>
      <tr>
        <th scope="row">Order Number</th>
        <td>#<%= @order.order_number %></td>
      </tr>
      <tr>
        <th scope="row">Patient Information</th>
        <td><%= @order.patient_name %>,<br>
          <%= @order.patient_email %><br>
          <%= @order.patient_contact %><br>
          <%= @order.patient_address %><br>
          <%= @order.patient_city %><br>
          <%= @order.patient_state %><br>
          <%= @order.patient_zipcode %><br>
      </tr>
      <tr>
        <th scope="row">Order Detail</th>
        <td>
          <%= @order.order_details %><br>
        </td>
      </tr>
    </table>
  </details>
</div>